language: java
sudo: false
install: true

addons:
  sonarqube:
    organization: "zyra83-github"
    token:
      secure: "uB6SN/uqTU71Ks6wRSGicDz+YFKkTpmBzi9FQEFb/d9frYbVbuqBlAdZXZQ5TWiicbZD8nVqrAvxZxjHZjlPFB+7yBq3S8MPgocknhKaCdunrTCuDXHM8oSu9xhYFFMftPRv01gN/Lxm6LPcImXFyDEcf+dOrROzrZnsFvAgwY5ikI9VN8ebi2mg87H/PHXgHeTiydQDGRzf5eudRuX/Ksz4CDLQ28oUHcC7pCMh23l55gTLRtMqo1gNiBm86/rQaQ/tngnV+1PDg6wlk69PZPnFLe6PPtjlfa+rnFddE4f89eKAXcc/nWE+TsR0m36R7HzNxX/t/Ind+8soiOjkuaeecyy0Xvlow25JWZh2es6KvZI3I4nrPhmiG5NAI5XMSOUZKUInXozYOl1Cmla4UOeIPGNFVpOrrTbPO4aNhym/tELgTXt58fhCq7vjocI9v+bHBw6WnvI8afE82pXg3dpUg3M+WkvrbbfBSjo587ZzYSl8c0X/51PBSnIfe0sEp4dyOTEIP94Y4WNup8iYlm1dCMCK5NLi+Da0g0zBOVrCEtMJ6UzyNUZ42uFvPaAVoomYSwEKd0YbkPSG9ZkM8fbd4Mmw9fcoKLNTkPo0DtLYGaXDtDnPUsPkCgii9/cbEDHkCr4lkakPAB4CWaNIjinf/AEobPumFguC7l0mvLY="
    github_token:
      secure: "CorG07HLyjc5e5daz6dYQe/AqpM5iboB2x4Vybhg4IB/7Cdbi4Lyz6neniKV3UVGWXLdBxxq2/8/ShqLOxaz0blbl1Ypl7lPfokDGdwXg8o/Bmwm5xBqcQAGdaLUXiHNCQgXR4xzoyN6tn9ZFpwDSBrKo25JyQI8ZCoVe7juoacRw2VYPc5jUurYzZ/Y952FGX5rL6nBBCBH47B7TGt8vNBqMpKEpLTp8UwqS9a77eSslBmo0TZA31ZjvpdbudGye/Mrdk/P4UX38TXodTlhQGB14e3wxGI58tORStCa6rWdyBG4knCjXB0NnbkeFn7tgzrwlrPKiwMpzfbhegZRixwZ8HaEQ6koNUoQv1aTOiOqk+MY6K9RD6uNGO2RBrysoAn7ZANh/NxrDdzU8kIr7rM3nMzjHVlzynu0ExGf6qOJkhu/t6RVWp3142AdDKfs/42AiAyZf5DAxsgZL37sGkaVwF+UJiTjk8i+GUXmxGa3/48YtuV1Grso4G8cxOa8M4tMYrxhHUwmx088uCe3FwejQZpPFIx1QGHp1jP01Lu29Al/BkrNi/DAtYxKSNfWoJit3QdIpAAFo5qn5+edSBEF4rNCg2h9j+bV52C+NqlPG1UUwsCuPnZagmuU+cquugqQRFBc8KyKHcleydzttjHuDAhwo7BCbzcZqjDNgjA="

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of mvn deploy
  - rm -rf $HOME/.m2/repository/fr/zyra
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;
